# Form implementation generated from reading ui file 'SettingsWindow.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal
from PyQt6.QtCore import QObject


class Ui_Settings(QtCore.QObject):

    exposure_auto_changed = pyqtSignal(bool)
    exposure_value_changed = pyqtSignal(int)


    def __init__(self):
        super(Ui_Settings, self).__init__()
        #self.image_acquirer = image_acquirer

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(329, 189)
        self.ConfirmButtonBox = QtWidgets.QDialogButtonBox(Form)
        self.ConfirmButtonBox.setGeometry(QtCore.QRect(150, 150, 156, 23))
        self.ConfirmButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.ConfirmButtonBox.setObjectName("ConfirmButtonBox")
        self.ExposureSlider = QtWidgets.QSlider(Form)
        self.ExposureSlider.setGeometry(QtCore.QRect(20, 30, 160, 20))
        self.ExposureSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.ExposureSlider.setObjectName("ExposureSlider")
        self.ExposureSlider.setMaximum(62250)
        self.ExposureLabel = QtWidgets.QLabel(Form)
        self.ExposureLabel.setGeometry(QtCore.QRect(20, 10, 50, 15))
        self.ExposureLabel.setObjectName("ExposureLabel")
        self.GainSlider = QtWidgets.QSlider(Form)
        self.GainSlider.setGeometry(QtCore.QRect(20, 100, 160, 20))
        self.GainSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.GainSlider.setObjectName("GainSlider")
        self.GainLabel = QtWidgets.QLabel(Form)
        self.GainLabel.setGeometry(QtCore.QRect(20, 80, 50, 15))
        self.GainLabel.setObjectName("GainLabel")
        self.AutoExposureBox = QtWidgets.QCheckBox(Form)
        self.AutoExposureBox.setGeometry(QtCore.QRect(260, 30, 70, 20))
        self.AutoExposureBox.setObjectName("AutoExposureBox")
        self.AutoGainBox = QtWidgets.QCheckBox(Form)
        self.AutoGainBox.setGeometry(QtCore.QRect(260, 100, 70, 20))
        self.AutoGainBox.setObjectName("AutoGainBox")
        self.ExposureValueLabel = QtWidgets.QLabel(Form)
        self.ExposureValueLabel.setGeometry(QtCore.QRect(190, 30, 50, 20))
        self.ExposureValueLabel.setObjectName("ExposureValueLabel")
        self.GainValueLabel = QtWidgets.QLabel(Form)
        self.GainValueLabel.setGeometry(QtCore.QRect(190, 100, 47, 20))
        self.GainValueLabel.setObjectName("GainValueLabel")

        # Connections of buttons with functions
        self.AutoExposureBox.clicked.connect(self.auto_exposure_change)
        self.ExposureSlider.valueChanged.connect(self.exposure_change)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ExposureLabel.setText(_translate("Form", "Exposure"))
        self.GainLabel.setText(_translate("Form", "Gain"))
        self.AutoExposureBox.setText(_translate("Form", "Auto"))
        self.AutoGainBox.setText(_translate("Form", "Auto"))
        self.ExposureValueLabel.setText(_translate("Form", "TextLabel"))
        self.GainValueLabel.setText(_translate("Form", "TextLabel"))

    def auto_exposure_change(self):
        if self.AutoExposureBox.isChecked() == True:
            self.ExposureSlider.setDisabled(True)
        else:
            self.ExposureSlider.setEnabled(True)
        self.exposure_auto_changed.emit(self.AutoExposureBox.isChecked())

    def exposure_change(self):
        self.ExposureValueLabel.setText(str(self.ExposureSlider.value()))
        self.exposure_value_changed.emit(self.ExposureSlider.value())